from __future__ import annotations

import json
import logging
import re
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime, timezone
from math import ceil
from pathlib import Path
from time import perf_counter
from typing import Any

import httpx
from json_repair import repair_json
from openai import OpenAI
from openai.types.chat import ChatCompletionMessageParam
from openai.types.chat.chat_completion_system_message_param import ChatCompletionSystemMessageParam
from openai.types.chat.chat_completion_user_message_param import ChatCompletionUserMessageParam

from lsl.core.config import Settings
from lsl.modules.revision.types import (
    RevisionGenerateRequest,
    RevisionGenerator,
    RevisionPromptUtterance,
    RevisionSegment,
    RevisionSuggestion,
)

logger = logging.getLogger(__name__)

_CODE_FENCE_JSON_RE = re.compile(r"```(?:json)?\s*(.+?)\s*```", re.DOTALL | re.IGNORECASE)
_SPLIT_TEXT_RE = re.compile(r"[,/，、\n]+")
_MAX_ISSUE_TAGS = 4
_SEGMENT_TARGET_UTTERANCE_COUNT = 24
_SEGMENT_HARD_MAX_UTTERANCE_COUNT = 32
_SEGMENT_CONTEXT_UTTERANCE_COUNT = 2
_SEGMENT_MAX_WORKERS = 4

_SEGMENT_PLAN_SYSTEM_PROMPT = """You are planning revision batches for a spoken-English transcript.

Your task is to divide the transcript into contiguous topic-based sections before sentence-level revision.

Important rules:
- Return a JSON object only.
- Cover every utterance exactly once.
- Segments must be contiguous by utterance_seq, with no gaps and no overlaps.
- Prefer split points where the topic, activity, or discussion phase changes.
- Keep each segment reasonably small for downstream revision.
- Most segments should contain about 16 to 28 target utterances.
- Never merge unrelated topics just to reduce the number of segments.
- Give each segment a short Chinese title and a short Chinese summary.

Output schema:
{
  "segments": [
    {
      "segment_index": 1,
      "start_seq": 0,
      "end_seq": 23,
      "title": "寒暄与近况",
      "summary": "内容: 双方通过语音软件，先打招呼，随后聊到今天是否忙、工作安排等。结果: speaker2 今天的工作内容1)完成软件的bug 修复.2)和客户开会讨论需求.3)整理会议纪要. speaker1 今天的工作内容1)完成了一个项目的测试.2)和同事讨论了项目进度.3)准备了明天的会议材料."
    }
  ]
}
"""

_SEGMENT_REVISION_SYSTEM_PROMPT = """You are an expert English speaking coach for oral English classes.

Your task is to revise only the target utterances and return a JSON object only.

Goals for each target utterance:
1. Rewrite the original text into fluent, natural spoken English.
2. Preserve the original meaning, intent, and speaker perspective.
3. Score the ORIGINAL sentence from 0 to 100 based on grammar, clarity, and naturalness.
4. Provide short Chinese issue tags and short Chinese explanations for improvement.
5. Provide one short Chinese delivery cue sentence that can be shown before the rewritten sentence.

Important rules:
- Use the segment title, segment summary, and nearby context only for understanding.
- Return items only for target_utterances. Do not return context utterances.
- Return every target utterance with the same utterance_seq as the input.
- Keep edits minimal if the sentence is already natural.
- Do not invent facts, change tense without reason, or change the speaker's intent.
- Prefer one natural spoken sentence. Two short sentences are acceptable when needed.
- issue_tags should be one comma-separated Chinese string such as "不够自然, 语法错误".
- explanations should be one concise Chinese string.
- suggested_cue should be a short Chinese direction such as "用轻松自然的语气开口，像在跟朋友随口聊天。"
- Use strict JSON that can be parsed by Python json.loads.
- Do not include trailing commas before } or ].
- Return JSON only. No markdown. No extra text.

Output schema:
{
  "items": [
    {
      "utterance_seq": 1,
      "suggested_text": "What did you do last weekend?",
      "suggested_cue": "有点好奇的,用轻松又带点分享欲的语气读这句,像是在和朋友聊周末经历.",
      "score": 88,
      "issue_tags": "不够自然, 语法错误",
      "explanations": "把表达改得更符合日常口语，并根据聊天上下文把时态调整正确。"
    }
  ]
}
"""


def create_revision_generator(settings: Settings) -> RevisionGenerator:
    provider = (settings.REVISION_PROVIDER or "fake").strip().lower()
    if provider == "llm":
        return LLMRevisionGenerator(settings)
    if provider == "fake":
        return FakeRevisionGenerator()
    raise ValueError(f"Unsupported REVISION_PROVIDER: {provider}")


class FakeRevisionGenerator:
    provider_name = "fake"

    def generate(self, req: RevisionGenerateRequest) -> list[RevisionSuggestion]:
        suggestions: list[RevisionSuggestion] = []
        for item in req.utterances:
            suggestions.append(
                RevisionSuggestion(
                    utterance_seq=int(item.utterance_seq),
                    suggested_text="This is a fake revised sentence for debugging.",
                    suggested_cue="用夸张又兴奋的语气读这句，像是在调试时故意把情绪拉满。",
                    score=78,
                    issue_tags="调试文案",
                    explanations="Generated by FakeRevisionGenerator for local debugging.",
                )
            )
        return suggestions


class LLMRevisionGenerator:
    provider_name = "llm"

    def __init__(self, settings: Settings) -> None:
        self._api_key = settings.REVISION_LLM_API_KEY
        self._base_url = settings.REVISION_LLM_BASE_URL
        self._model = settings.REVISION_LLM_MODEL
        self._timeout = float(settings.REVISION_LLM_HTTP_TIMEOUT)
        self._debug_file = settings.REVISION_LLM_DEBUG_FILE.strip()
        self._client: OpenAI | None = None

    def generate(self, req: RevisionGenerateRequest) -> list[RevisionSuggestion]:
        if not req.utterances:
            return []

        segments = self._plan_segments(
            task_id=req.task_id,
            utterances=req.utterances,
            user_prompt=req.user_prompt,
        )
        suggestions = self._generate_segmented_revisions(
            task_id=req.task_id,
            utterances=req.utterances,
            user_prompt=req.user_prompt,
            segments=segments,
        )
        return self._deduplicate_suggestions(suggestions)

    def _plan_segments(
        self,
        *,
        task_id: str,
        utterances: list[RevisionPromptUtterance],
        user_prompt: str | None,
    ) -> list[RevisionSegment]:
        content = self._request_chat_completion(
            task_id=task_id,
            request_name="segment_plan",
            messages=self._build_segment_plan_messages(
                task_id=task_id,
                utterances=utterances,
                user_prompt=user_prompt,
            ),
        )
        segments = self._parse_segment_plan_response(content=content, utterances=utterances)
        return self._split_oversized_segments(segments)

    def _generate_segmented_revisions(
        self,
        *,
        task_id: str,
        utterances: list[RevisionPromptUtterance],
        user_prompt: str | None,
        segments: list[RevisionSegment],
    ) -> list[RevisionSuggestion]:
        if not segments:
            return []

        utterance_index_by_seq = {int(item.utterance_seq): index for index, item in enumerate(utterances)}
        max_workers = max(1, min(_SEGMENT_MAX_WORKERS, len(segments)))
        suggestions: list[RevisionSuggestion] = []

        with ThreadPoolExecutor(max_workers=max_workers) as executor:
            futures = {
                executor.submit(
                    self._generate_single_segment_revision,
                    task_id=task_id,
                    utterances=utterances,
                    user_prompt=user_prompt,
                    segment=segment,
                    utterance_index_by_seq=utterance_index_by_seq,
                ): segment
                for segment in segments
            }
            for future in as_completed(futures):
                segment = futures[future]
                try:
                    suggestions.extend(future.result())
                except Exception as exc:
                    raise RuntimeError(
                        f"Segment revision failed for seq range {segment.start_seq}-{segment.end_seq}: {exc}"
                    ) from exc
        return suggestions

    def _generate_single_segment_revision(
        self,
        *,
        task_id: str,
        utterances: list[RevisionPromptUtterance],
        user_prompt: str | None,
        segment: RevisionSegment,
        utterance_index_by_seq: dict[int, int],
    ) -> list[RevisionSuggestion]:
        start_index = utterance_index_by_seq.get(int(segment.start_seq))
        end_index = utterance_index_by_seq.get(int(segment.end_seq))
        if start_index is None or end_index is None or start_index > end_index:
            raise RuntimeError(f"Invalid segment bounds: {segment.start_seq}-{segment.end_seq}")

        target_utterances = utterances[start_index : end_index + 1]
        context_before = utterances[max(0, start_index - _SEGMENT_CONTEXT_UTTERANCE_COUNT) : start_index]
        context_after = utterances[end_index + 1 : end_index + 1 + _SEGMENT_CONTEXT_UTTERANCE_COUNT]

        request_name = f"segment_revision[{segment.segment_index}][{segment.start_seq}-{segment.end_seq}]"
        content = self._request_chat_completion(
            task_id=task_id,
            request_name=request_name,
            messages=self._build_segment_revision_messages(
                task_id=task_id,
                segment=segment,
                user_prompt=user_prompt,
                context_before=context_before,
                target_utterances=target_utterances,
                context_after=context_after,
            ),
        )
        return self._parse_revision_response(content=content, utterances=target_utterances)

    def _request_chat_completion(
        self,
        *,
        task_id: str,
        request_name: str,
        messages: list[ChatCompletionMessageParam],
    ) -> str:
        client = self._get_client()
        started_at = datetime.now(timezone.utc)
        started_perf = perf_counter()
        logger.info(
            "LLM request started task_id=%s request_name=%s model=%s started_at=%s",
            task_id,
            request_name,
            self._model,
            started_at.isoformat(),
        )

        content: str | None = None
        error_message: str | None = None
        finish_reason: str | None = None
        try:
            response = client.chat.completions.create(
                model=self._model,
                temperature=0.2,
                messages=messages,
                timeout=self._timeout,
                reasoning_effort="minimal",
            )
            if not response.choices:
                raise RuntimeError("LLM returned no choices")

            choice = response.choices[0]
            finish_reason = getattr(choice, "finish_reason", None)
            content = choice.message.content
            if content is None or not content.strip():
                raise RuntimeError("LLM returned empty content")
            if finish_reason not in (None, "stop"):
                raise RuntimeError(f"LLM stopped with finish_reason={finish_reason}")
            return content
        except Exception as exc:
            error_message = str(exc)
            raise
        finally:
            finished_at = datetime.now(timezone.utc)
            duration_ms = int((perf_counter() - started_perf) * 1000)
            self._append_debug_dump(
                task_id=task_id,
                request_name=request_name,
                messages=messages,
                started_at=started_at,
                finished_at=finished_at,
                duration_ms=duration_ms,
                response_content=content,
                error_message=error_message,
                finish_reason=finish_reason,
            )
            if error_message is None:
                logger.info(
                    "LLM request finished task_id=%s request_name=%s model=%s finished_at=%s duration_ms=%s",
                    task_id,
                    request_name,
                    self._model,
                    finished_at.isoformat(),
                    duration_ms,
                )
            else:
                logger.error(
                    "LLM request failed task_id=%s request_name=%s model=%s finished_at=%s duration_ms=%s error=%s",
                    task_id,
                    request_name,
                    self._model,
                    finished_at.isoformat(),
                    duration_ms,
                    error_message,
                )

    def _build_segment_plan_messages(
        self,
        *,
        task_id: str,
        utterances: list[RevisionPromptUtterance],
        user_prompt: str | None,
    ) -> list[ChatCompletionMessageParam]:
        payload = {
            "task_id": task_id,
            "user_prompt": (user_prompt or "").strip(),
            "utterances": [
                {
                    "utterance_seq": int(item.utterance_seq),
                    "speaker": item.speaker,
                    "text": item.text,
                }
                for item in utterances
            ],
        }
        user_content = (
            "Plan coherent revision segments for the following transcript.\n"
            "Input JSON:\n"
            f"{json.dumps(payload, ensure_ascii=False, indent=2)}"
        )
        system_message: ChatCompletionSystemMessageParam = {
            "role": "system",
            "content": _SEGMENT_PLAN_SYSTEM_PROMPT,
        }
        user_message: ChatCompletionUserMessageParam = {
            "role": "user",
            "content": user_content,
        }
        return [system_message, user_message]

    def _build_segment_revision_messages(
        self,
        *,
        task_id: str,
        segment: RevisionSegment,
        user_prompt: str | None,
        context_before: list[RevisionPromptUtterance],
        target_utterances: list[RevisionPromptUtterance],
        context_after: list[RevisionPromptUtterance],
    ) -> list[ChatCompletionMessageParam]:
        payload = {
            "task_id": task_id,
            "user_prompt": (user_prompt or "").strip(),
            "segment": {
                "segment_index": int(segment.segment_index),
                "start_seq": int(segment.start_seq),
                "end_seq": int(segment.end_seq),
                "title": segment.title,
                "summary": segment.summary,
            },
            "context_before": [self._serialize_prompt_utterance(item) for item in context_before],
            "target_utterances": [self._serialize_prompt_utterance(item) for item in target_utterances],
            "context_after": [self._serialize_prompt_utterance(item) for item in context_after],
        }
        user_content = (
            "Revise the target utterances from the following spoken-English transcript segment.\n"
            "Use the segment summary and nearby context only for understanding.\n"
            "Input JSON:\n"
            f"{json.dumps(payload, ensure_ascii=False, indent=2)}"
        )
        system_message: ChatCompletionSystemMessageParam = {
            "role": "system",
            "content": _SEGMENT_REVISION_SYSTEM_PROMPT,
        }
        user_message: ChatCompletionUserMessageParam = {
            "role": "user",
            "content": user_content,
        }
        return [system_message, user_message]

    @staticmethod
    def _serialize_prompt_utterance(item: RevisionPromptUtterance) -> dict[str, Any]:
        payload: dict[str, Any] = {
            "utterance_seq": int(item.utterance_seq),
            "speaker": item.speaker,
            "text": item.text,
        }
        if item.addions:
            payload["addions"] = item.addions
        return payload

    def _parse_segment_plan_response(
        self,
        *,
        content: str,
        utterances: list[RevisionPromptUtterance],
    ) -> list[RevisionSegment]:
        parsed = self._loads_json(content)
        raw_segments = self._extract_segments(parsed)
        if not raw_segments:
            raise RuntimeError("LLM returned no revision segments")

        segments: list[RevisionSegment] = []
        for index, raw_segment in enumerate(raw_segments, start=1):
            if not isinstance(raw_segment, dict):
                continue
            segment = self._normalize_segment(raw_segment=raw_segment, default_index=index)
            if segment is not None:
                segments.append(segment)

        if not segments:
            raise RuntimeError("LLM returned no valid revision segments")

        return self._validate_segment_plan(segments=segments, utterances=utterances)

    def _normalize_segment(
        self,
        *,
        raw_segment: dict[str, Any],
        default_index: int,
    ) -> RevisionSegment | None:
        start_seq = self._coerce_int(raw_segment.get("start_seq"))
        end_seq = self._coerce_int(raw_segment.get("end_seq"))
        if start_seq is None or end_seq is None or start_seq > end_seq:
            return None

        segment_index = self._coerce_int(raw_segment.get("segment_index")) or default_index
        title = self._normalize_brief_text(raw_segment.get("title"))
        summary = self._normalize_brief_text(raw_segment.get("summary"))
        return RevisionSegment(
            segment_index=int(segment_index),
            start_seq=int(start_seq),
            end_seq=int(end_seq),
            title=title,
            summary=summary,
        )

    def _validate_segment_plan(
        self,
        *,
        segments: list[RevisionSegment],
        utterances: list[RevisionPromptUtterance],
    ) -> list[RevisionSegment]:
        expected_seqs = [int(item.utterance_seq) for item in utterances]
        if not expected_seqs:
            return []

        normalized_segments = sorted(segments, key=lambda item: (int(item.start_seq), int(item.end_seq)))
        covered_seqs: list[int] = []
        final_segments: list[RevisionSegment] = []
        for index, segment in enumerate(normalized_segments, start=1):
            final_segments.append(
                RevisionSegment(
                    segment_index=index,
                    start_seq=int(segment.start_seq),
                    end_seq=int(segment.end_seq),
                    title=segment.title,
                    summary=segment.summary,
                )
            )
            covered_seqs.extend(range(int(segment.start_seq), int(segment.end_seq) + 1))

        if covered_seqs != expected_seqs:
            raise RuntimeError("LLM segment plan does not fully cover utterance_seq without gaps or overlaps")
        return final_segments

    def _split_oversized_segments(self, segments: list[RevisionSegment]) -> list[RevisionSegment]:
        normalized_segments: list[RevisionSegment] = []
        next_index = 1
        for segment in segments:
            segment_size = int(segment.end_seq) - int(segment.start_seq) + 1
            if segment_size <= _SEGMENT_HARD_MAX_UTTERANCE_COUNT:
                normalized_segments.append(
                    RevisionSegment(
                        segment_index=next_index,
                        start_seq=int(segment.start_seq),
                        end_seq=int(segment.end_seq),
                        title=segment.title,
                        summary=segment.summary,
                    )
                )
                next_index += 1
                continue

            part_count = ceil(segment_size / _SEGMENT_TARGET_UTTERANCE_COUNT)
            current_start = int(segment.start_seq)
            for part_index in range(1, part_count + 1):
                current_end = min(
                    int(segment.end_seq),
                    current_start + _SEGMENT_TARGET_UTTERANCE_COUNT - 1,
                )
                suffix = f" (part {part_index}/{part_count})"
                normalized_segments.append(
                    RevisionSegment(
                        segment_index=next_index,
                        start_seq=current_start,
                        end_seq=current_end,
                        title=f"{segment.title}{suffix}" if segment.title else f"Segment {next_index}",
                        summary=segment.summary,
                    )
                )
                next_index += 1
                current_start = current_end + 1
        return normalized_segments

    def _parse_revision_response(
        self,
        *,
        content: str,
        utterances: list[RevisionPromptUtterance],
    ) -> list[RevisionSuggestion]:
        parsed = self._loads_json(content)
        raw_items = self._extract_items(parsed)
        if not raw_items:
            raise RuntimeError("LLM returned no revision items")

        utterance_by_seq = {int(item.utterance_seq): item for item in utterances}
        suggestions: list[RevisionSuggestion] = []
        for raw_item in raw_items:
            if not isinstance(raw_item, dict):
                continue
            suggestion = self._normalize_suggestion(raw_item=raw_item, utterance_by_seq=utterance_by_seq)
            if suggestion is not None:
                suggestions.append(suggestion)
        return suggestions

    def _normalize_suggestion(
        self,
        *,
        raw_item: dict[str, Any],
        utterance_by_seq: dict[int, RevisionPromptUtterance],
    ) -> RevisionSuggestion | None:
        utterance_seq = self._coerce_int(raw_item.get("utterance_seq"))
        if utterance_seq is None:
            return None

        if utterance_seq not in utterance_by_seq:
            return None

        issue_tags_list = self._normalize_string_list(raw_item.get("issue_tags"), max_items=_MAX_ISSUE_TAGS)
        explanations_text = self._normalize_explanations_text(raw_item.get("explanations"))
        score = self._require_score(raw_item.get("score"), utterance_seq=utterance_seq)

        return RevisionSuggestion(
            utterance_seq=utterance_seq,
            suggested_text=self._require_text(
                raw_item.get("suggested_text"),
                field_name="suggested_text",
                utterance_seq=utterance_seq,
            ),
            suggested_cue=self._normalize_cue_text(raw_item.get("suggested_cue")),
            score=score,
            issue_tags=", ".join(issue_tags_list),
            explanations=explanations_text,
        )

    def _get_client(self) -> OpenAI:
        if self._client is not None:
            return self._client
        if not self._api_key:
            raise RuntimeError("REVISION_LLM_API_KEY is not configured")
        if not self._base_url:
            raise RuntimeError("REVISION_LLM_BASE_URL is not configured")
        if not self._model:
            raise RuntimeError("REVISION_LLM_MODEL is not configured")

        http_client = httpx.Client(timeout=self._timeout, trust_env=False)
        self._client = OpenAI(
            api_key=self._api_key,
            base_url=self._base_url,
            http_client=http_client,
        )
        return self._client

    def _append_debug_dump(
        self,
        *,
        task_id: str,
        request_name: str,
        messages: list[ChatCompletionMessageParam],
        started_at: datetime,
        finished_at: datetime,
        duration_ms: int,
        response_content: str | None,
        error_message: str | None,
        finish_reason: str | None,
    ) -> None:
        if not self._debug_file:
            return

        debug_path = Path(self._debug_file).expanduser()
        debug_path.parent.mkdir(parents=True, exist_ok=True)
        dump_lines = [
            "===== LLM Revision Request =====",
            f"request_name: {request_name}",
            f"task_id: {task_id}",
            f"model: {self._model}",
            f"started_at: {started_at.isoformat()}",
            f"finished_at: {finished_at.isoformat()}",
            f"duration_ms: {duration_ms}",
            f"finish_reason: {finish_reason or ''}",
            "",
            "[messages]",
            json.dumps(messages, ensure_ascii=False, indent=2),
            "",
            "[response]",
            response_content or "",
        ]
        if error_message:
            dump_lines.extend(
                [
                    "",
                    "[error]",
                    error_message,
                ]
            )
        dump_lines.extend(["", ""])
        try:
            with debug_path.open("a", encoding="utf-8") as file:
                file.write("\n".join(dump_lines))
        except OSError as exc:
            logger.warning("Failed to write LLM revision debug dump %s: %s", debug_path, exc)

    @staticmethod
    def _normalize_cue_text(value: Any) -> str | None:
        if value is None:
            return None
        normalized = str(value).strip()
        return normalized or None

    @staticmethod
    def _normalize_explanations_text(value: Any) -> str:
        if value is None:
            return ""
        if isinstance(value, str):
            return re.sub(r"\s+", " ", value).strip()
        if isinstance(value, list):
            parts = [re.sub(r"\s+", " ", str(item)).strip() for item in value if str(item).strip()]
            return " ".join(parts)
        return re.sub(r"\s+", " ", str(value)).strip()

    @staticmethod
    def _normalize_brief_text(value: Any) -> str:
        if value is None:
            return ""
        return re.sub(r"\s+", " ", str(value)).strip()

    @staticmethod
    def _deduplicate_suggestions(suggestions: list[RevisionSuggestion]) -> list[RevisionSuggestion]:
        deduplicated: list[RevisionSuggestion] = []
        seen_seqs: set[int] = set()
        for suggestion in sorted(suggestions, key=lambda item: int(item.utterance_seq)):
            utterance_seq = int(suggestion.utterance_seq)
            if utterance_seq in seen_seqs:
                continue
            deduplicated.append(suggestion)
            seen_seqs.add(utterance_seq)
        return deduplicated

    @staticmethod
    def _loads_json(content: str) -> Any:
        candidates: list[str] = []
        initial_candidate = content.strip()
        if initial_candidate:
            candidates.append(initial_candidate)

        fenced_match = _CODE_FENCE_JSON_RE.search(content)
        if fenced_match is not None:
            fenced_candidate = fenced_match.group(1).strip()
            if fenced_candidate:
                candidates.append(fenced_candidate)

        start = min((index for index in (content.find("{"), content.find("[")) if index >= 0), default=-1)
        if start >= 0:
            for open_char, close_char in (("{", "}"), ("[", "]")):
                open_index = content.find(open_char, start)
                close_index = content.rfind(close_char)
                if open_index >= 0 and close_index > open_index:
                    extracted_candidate = content[open_index : close_index + 1].strip()
                    if extracted_candidate:
                        candidates.append(extracted_candidate)

        if not candidates:
            raise RuntimeError("Unable to locate JSON in LLM response")

        last_error: Exception | None = None
        seen_candidates: set[str] = set()
        for candidate in candidates:
            if candidate in seen_candidates:
                continue
            seen_candidates.add(candidate)
            try:
                return json.loads(candidate)
            except json.JSONDecodeError as exc:
                last_error = exc

            try:
                return repair_json(candidate, return_objects=True, skip_json_loads=True)
            except Exception as exc:  # pragma: no cover
                last_error = exc

        if last_error is not None:
            message = getattr(last_error, "msg", str(last_error)) or "unknown parse error"
            raise RuntimeError(f"Unable to parse JSON from LLM response: {message}")
        raise RuntimeError("Unable to parse JSON from LLM response")

    @staticmethod
    def _extract_items(payload: Any) -> list[Any]:
        if isinstance(payload, list):
            return payload
        if isinstance(payload, dict):
            items = payload.get("items")
            if isinstance(items, list):
                return items
        return []

    @staticmethod
    def _extract_segments(payload: Any) -> list[Any]:
        if isinstance(payload, dict):
            segments = payload.get("segments")
            if isinstance(segments, list):
                return segments
        return []

    @staticmethod
    def _coerce_int(value: Any) -> int | None:
        if isinstance(value, bool):
            return None
        if isinstance(value, int):
            return value
        if isinstance(value, float):
            return int(value)
        if isinstance(value, str):
            stripped = value.strip()
            if not stripped:
                return None
            try:
                return int(float(stripped))
            except ValueError:
                return None
        return None

    @staticmethod
    def _require_text(value: Any, *, field_name: str, utterance_seq: int) -> str:
        text = re.sub(r"\s+", " ", str(value).strip()) if value is not None else ""
        if text:
            return text
        raise RuntimeError(f"LLM response missing {field_name} for utterance_seq={utterance_seq}")

    @staticmethod
    def _normalize_string_list(value: Any, *, max_items: int) -> list[str]:
        raw_items: list[str] = []
        if isinstance(value, str):
            raw_items = [part.strip() for part in _SPLIT_TEXT_RE.split(value)]
        elif isinstance(value, list):
            raw_items = [str(part).strip() for part in value]

        normalized: list[str] = []
        seen: set[str] = set()
        for item in raw_items:
            if not item:
                continue
            compact = re.sub(r"\s+", " ", item).strip()
            if not compact or compact in seen:
                continue
            normalized.append(compact)
            seen.add(compact)
            if len(normalized) >= max_items:
                break
        return normalized

    @staticmethod
    def _require_score(value: Any, *, utterance_seq: int) -> int:
        score = LLMRevisionGenerator._coerce_int(value)
        if score is None:
            raise RuntimeError(f"LLM response missing score for utterance_seq={utterance_seq}")
        if score < 0 or score > 100:
            raise RuntimeError(f"LLM response score out of range for utterance_seq={utterance_seq}: {score}")
        return int(score)
