from __future__ import annotations

import json
import logging
import re
from datetime import datetime, timezone
from pathlib import Path
from time import perf_counter
from typing import Any

import httpx
from openai import OpenAI
from openai.types.chat import ChatCompletionMessageParam
from openai.types.chat.chat_completion_system_message_param import ChatCompletionSystemMessageParam
from openai.types.chat.chat_completion_user_message_param import ChatCompletionUserMessageParam

from lsl.core.config import Settings
from lsl.modules.revision.types import (
    RevisionGenerateRequest,
    RevisionGenerator,
    RevisionPromptUtterance,
    RevisionSuggestion,
)

logger = logging.getLogger(__name__)

_CODE_FENCE_JSON_RE = re.compile(r"```(?:json)?\s*(.+?)\s*```", re.DOTALL | re.IGNORECASE)
_SPLIT_TEXT_RE = re.compile(r"[,/，、\n]+")
_TERMINAL_PUNCTUATION_RE = re.compile(r"[.!?]$")
_MAX_ISSUE_TAGS = 4
_MAX_EXPLANATIONS = 3

_SYSTEM_PROMPT = """You are an expert English speaking coach for oral English classes.

Your task is to review transcript utterances one by one and return a JSON object only.

Goals for each utterance:
1. Rewrite the original text into fluent, natural spoken English.
2. Preserve the original meaning, intent, and speaker perspective.
3. Score the ORIGINAL sentence from 0 to 100 based on grammar, clarity, and naturalness.
4. Provide short Chinese issue tags and short Chinese explanations for improvement.
5. Provide one short Chinese delivery cue sentence that can be shown before the rewritten sentence.

Important rules:
- Keep edits minimal if the sentence is already natural.
- Do not invent facts, change tense without reason, or change the speaker's intent.
- Prefer one natural spoken sentence. Two short sentences are acceptable when needed.
- issue_tags should be one comma-separated Chinese string such as "不够自然, 语法错误".
- explanations should be one concise Chinese string.
- suggested_cue should be a short Chinese direction such as "用轻松自然的语气开口，像在跟朋友随口聊天。"
- Return every utterance with the same utterance_seq as the input.
- Return JSON only. No markdown. No extra text.

Output schema:
{
  "items": [
    {
      "utterance_seq": 1,
      "suggested_text": "What did you do last weekend?",
      "suggested_cue": "有点好奇的,用轻松又带点分享欲的语气读这句,像是在和朋友聊周末经历.",
      "score": 88,
      "issue_tags": "不够自然, 语法错误",
      "explanations": "把表达改得更符合日常口语，并根据聊天上下文把时态调整正确。"
    }
  ]
}
"""


def create_revision_generator(settings: Settings) -> RevisionGenerator:
    provider = (settings.REVISION_PROVIDER or "fake").strip().lower()
    if provider == "llm":
        return LLMRevisionGenerator(settings)
    if provider == "fake":
        return FakeRevisionGenerator()
    raise ValueError(f"Unsupported REVISION_PROVIDER: {provider}")


class FakeRevisionGenerator:
    provider_name = "fake"

    def generate(self, req: RevisionGenerateRequest) -> list[RevisionSuggestion]:
        suggestions: list[RevisionSuggestion] = []
        for item in req.utterances:
            suggestions.append(
                RevisionSuggestion(
                    utterance_seq=int(item.utterance_seq),
                    suggested_text="This is a fake revised sentence for debugging.",
                    suggested_cue="用夸张又兴奋的语气读这句，像是在调试时故意把情绪拉满。",
                    score=78,
                    issue_tags="调试文案",
                    explanations="Generated by FakeRevisionGenerator for local debugging.",
                )
            )
        return suggestions


class LLMRevisionGenerator:
    provider_name = "llm"

    def __init__(self, settings: Settings) -> None:
        self._api_key = settings.REVISION_LLM_API_KEY
        self._base_url = settings.REVISION_LLM_BASE_URL
        self._model = settings.REVISION_LLM_MODEL
        self._timeout = float(settings.REVISION_LLM_HTTP_TIMEOUT)
        self._debug_file = settings.REVISION_LLM_DEBUG_FILE.strip()
        self._client: OpenAI | None = None

    def generate(self, req: RevisionGenerateRequest) -> list[RevisionSuggestion]:
        if not req.utterances:
            return []

        content = self._request_revision(
            task_id=req.task_id,
            utterances=req.utterances,
            user_prompt=req.user_prompt,
        )
        suggestions = self._parse_revision_response(content=content, utterances=req.utterances)
        # 去重是为了防止模型偶尔返回重复的utterance_seq，导致后续持久化时违反唯一约束
        return self._deduplicate_suggestions(suggestions)

    def _request_revision(
        self,
        *,
        task_id: str,
        utterances: list[RevisionPromptUtterance],
        user_prompt: str | None,
    ) -> str:
        client = self._get_client()
        messages = self._build_messages(
            task_id=task_id,
            utterances=utterances,
            user_prompt=user_prompt,
        )
        started_at = datetime.now(timezone.utc)
        started_perf = perf_counter()
        logger.info(
            "LLM revision request started task_id=%s model=%s utterance_count=%s started_at=%s",
            task_id,
            self._model,
            len(utterances),
            started_at.isoformat(),
        )

        content: str | None = None
        error_message: str | None = None
        try:
            response = client.chat.completions.create(
                model=self._model,
                temperature=0.2,
                messages=messages,
                timeout=self._timeout,
                reasoning_effort="minimal",
            )
            if not response.choices:
                raise RuntimeError("LLM returned no choices")

            content = response.choices[0].message.content
            if content is None or not content.strip():
                raise RuntimeError("LLM returned empty content")
            return content
        except Exception as exc:
            error_message = str(exc)
            raise
        finally:
            finished_at = datetime.now(timezone.utc)
            duration_ms = int((perf_counter() - started_perf) * 1000)
            self._append_debug_dump(
                task_id=task_id,
                messages=messages,
                started_at=started_at,
                finished_at=finished_at,
                duration_ms=duration_ms,
                response_content=content,
                error_message=error_message,
            )
            if error_message is None:
                logger.info(
                    "LLM revision request finished task_id=%s model=%s finished_at=%s duration_ms=%s",
                    task_id,
                    self._model,
                    finished_at.isoformat(),
                    duration_ms,
                )
            else:
                logger.error(
                    "LLM revision request failed task_id=%s model=%s finished_at=%s duration_ms=%s error=%s",
                    task_id,
                    self._model,
                    finished_at.isoformat(),
                    duration_ms,
                    error_message,
                )

    def _build_messages(
        self,
        *,
        task_id: str,
        utterances: list[RevisionPromptUtterance],
        user_prompt: str | None,
    ) -> list[ChatCompletionMessageParam]:
        payload = {
            "task_id": task_id,
            "user_prompt": (user_prompt or "").strip(),
            "utterances": [
                {
                    "utterance_seq": int(item.utterance_seq),
                    "speaker": item.speaker,
                    "text": item.text,
                    "start_time": int(item.start_time),
                    "end_time": int(item.end_time),
                    "addions": item.addions,
                }
                for item in utterances
            ],
        }
        user_content = (
            "Revise the following spoken-English transcript.\n"
            "Input JSON:\n"
            f"{json.dumps(payload, ensure_ascii=False, indent=2)}"
        )
        system_message: ChatCompletionSystemMessageParam = {
            "role": "system",
            "content": _SYSTEM_PROMPT,
        }
        user_message: ChatCompletionUserMessageParam = {
            "role": "user",
            "content": user_content,
        }
        return [system_message, user_message]

    def _parse_revision_response(
        self,
        *,
        content: str,
        utterances: list[RevisionPromptUtterance],
    ) -> list[RevisionSuggestion]:
        parsed = self._loads_json(content)
        raw_items = self._extract_items(parsed)
        if not raw_items:
            raise RuntimeError("LLM returned no revision items")

        utterance_by_seq = {int(item.utterance_seq): item for item in utterances}
        suggestions: list[RevisionSuggestion] = []
        for raw_item in raw_items:
            if not isinstance(raw_item, dict):
                continue
            suggestion = self._normalize_suggestion(raw_item=raw_item, utterance_by_seq=utterance_by_seq)
            if suggestion is not None:
                suggestions.append(suggestion)
        return suggestions

    def _normalize_suggestion(
        self,
        *,
        raw_item: dict[str, Any],
        utterance_by_seq: dict[int, RevisionPromptUtterance],
    ) -> RevisionSuggestion | None:
        utterance_seq = self._coerce_int(raw_item.get("utterance_seq"))
        if utterance_seq is None:
            return None

        utterance = utterance_by_seq.get(utterance_seq)
        if utterance is None:
            return None

        issue_tags_list = self._normalize_string_list(raw_item.get("issue_tags"), max_items=_MAX_ISSUE_TAGS)
        explanations_text = self._normalize_explanations_text(raw_item.get("explanations"))
        score = self._normalize_score(raw_item.get("score"), issue_tags=issue_tags_list)

        return RevisionSuggestion(
            utterance_seq=utterance_seq,
            suggested_text=self._normalize_sentence(raw_item.get("suggested_text"), fallback=utterance.text),
            suggested_cue=self._normalize_cue_text(raw_item.get("suggested_cue")),
            score=score,
            issue_tags=", ".join(issue_tags_list),
            explanations=explanations_text,
        )

    def _get_client(self) -> OpenAI:
        if self._client is not None:
            return self._client
        if not self._api_key:
            raise RuntimeError("REVISION_LLM_API_KEY is not configured")
        if not self._base_url:
            raise RuntimeError("REVISION_LLM_BASE_URL is not configured")
        if not self._model:
            raise RuntimeError("REVISION_LLM_MODEL is not configured")

        http_client = httpx.Client(timeout=self._timeout, trust_env=False)
        self._client = OpenAI(
            api_key=self._api_key,
            base_url=self._base_url,
            http_client=http_client,
        )
        return self._client

    def _append_debug_dump(
        self,
        *,
        task_id: str,
        messages: list[ChatCompletionMessageParam],
        started_at: datetime,
        finished_at: datetime,
        duration_ms: int,
        response_content: str | None,
        error_message: str | None,
    ) -> None:
        if not self._debug_file:
            return

        debug_path = Path(self._debug_file).expanduser()
        debug_path.parent.mkdir(parents=True, exist_ok=True)
        dump_lines = [
            "===== LLM Revision Request =====",
            f"task_id: {task_id}",
            f"model: {self._model}",
            f"started_at: {started_at.isoformat()}",
            f"finished_at: {finished_at.isoformat()}",
            f"duration_ms: {duration_ms}",
            "",
            "[messages]",
            json.dumps(messages, ensure_ascii=False, indent=2),
            "",
            "[response]",
            response_content or "",
        ]
        if error_message:
            dump_lines.extend(
                [
                    "",
                    "[error]",
                    error_message,
                ]
            )
        dump_lines.extend(["", ""])
        try:
            with debug_path.open("a", encoding="utf-8") as file:
                file.write("\n".join(dump_lines))
        except OSError as exc:
            logger.warning("Failed to write LLM revision debug dump %s: %s", debug_path, exc)

    @staticmethod
    def _normalize_cue_text(value: Any) -> str | None:
        if value is None:
            return None
        normalized = str(value).strip()
        return normalized or None

    @staticmethod
    def _normalize_explanations_text(value: Any) -> str:
        if value is None:
            return ""
        if isinstance(value, str):
            return re.sub(r"\s+", " ", value).strip()
        if isinstance(value, list):
            parts = [re.sub(r"\s+", " ", str(item)).strip() for item in value if str(item).strip()]
            return " ".join(parts)
        return re.sub(r"\s+", " ", str(value)).strip()

    @staticmethod
    def _deduplicate_suggestions(suggestions: list[RevisionSuggestion]) -> list[RevisionSuggestion]:
        # The model may occasionally return the same utterance_seq more than once.
        # We sort by seq for stable output order and keep only the first item for
        # each seq, so downstream persistence does not hit unique constraints.
        deduplicated: list[RevisionSuggestion] = []
        seen_seqs: set[int] = set()
        for suggestion in sorted(suggestions, key=lambda item: int(item.utterance_seq)):
            utterance_seq = int(suggestion.utterance_seq)
            if utterance_seq in seen_seqs:
                continue
            deduplicated.append(suggestion)
            seen_seqs.add(utterance_seq)
        return deduplicated

    @staticmethod
    def _loads_json(content: str) -> Any:
        candidate = content.strip()
        try:
            return json.loads(candidate)
        except json.JSONDecodeError:
            pass

        fenced_match = _CODE_FENCE_JSON_RE.search(content)
        if fenced_match is not None:
            candidate = fenced_match.group(1).strip()
            try:
                return json.loads(candidate)
            except json.JSONDecodeError:
                pass

        start = min((index for index in (content.find("{"), content.find("[")) if index >= 0), default=-1)
        if start < 0:
            raise RuntimeError("Unable to locate JSON in LLM response")

        for open_char, close_char in (("{", "}"), ("[", "]")):
            open_index = content.find(open_char, start)
            close_index = content.rfind(close_char)
            if open_index >= 0 and close_index > open_index:
                candidate = content[open_index : close_index + 1].strip()
                try:
                    return json.loads(candidate)
                except json.JSONDecodeError:
                    continue

        raise RuntimeError("Unable to parse JSON from LLM response")

    @staticmethod
    def _extract_items(payload: Any) -> list[Any]:
        if isinstance(payload, list):
            return payload
        if isinstance(payload, dict):
            items = payload.get("items")
            if isinstance(items, list):
                return items
        return []

    @staticmethod
    def _coerce_int(value: Any) -> int | None:
        if isinstance(value, bool):
            return None
        if isinstance(value, int):
            return value
        if isinstance(value, float):
            return int(value)
        if isinstance(value, str):
            stripped = value.strip()
            if not stripped:
                return None
            try:
                return int(float(stripped))
            except ValueError:
                return None
        return None

    @staticmethod
    def _normalize_sentence(value: Any, *, fallback: str) -> str:
        text = str(value).strip() if value is not None else ""
        if not text:
            text = fallback.strip()
        text = re.sub(r"\s+", " ", text).strip()
        if not text:
            return fallback.strip()
        if text[0].isalpha() and text[0].islower():
            text = f"{text[0].upper()}{text[1:]}"
        if not _TERMINAL_PUNCTUATION_RE.search(text):
            text = f"{text}."
        return text

    @staticmethod
    def _normalize_string_list(value: Any, *, max_items: int) -> list[str]:
        raw_items: list[str] = []
        if isinstance(value, str):
            raw_items = [part.strip() for part in _SPLIT_TEXT_RE.split(value)]
        elif isinstance(value, list):
            raw_items = [str(part).strip() for part in value]

        normalized: list[str] = []
        seen: set[str] = set()
        for item in raw_items:
            if not item:
                continue
            compact = re.sub(r"\s+", " ", item).strip()
            if not compact or compact in seen:
                continue
            normalized.append(compact)
            seen.add(compact)
            if len(normalized) >= max_items:
                break
        return normalized

    @staticmethod
    def _normalize_score(value: Any, *, issue_tags: list[str]) -> int:
        score = LLMRevisionGenerator._coerce_int(value)
        if score is None:
            lowered = " ".join(issue_tags).lower()
            score = 88
            if any(token in lowered for token in ("语法", "时态", "主谓")):
                score -= 22
            if any(token in lowered for token in ("不够自然", "搭配", "表达不清", "用词")):
                score -= 12
            if any(token in lowered for token in ("标点", "大小写")):
                score -= 6
            if "表达基本自然" in issue_tags:
                score = max(score, 92)
        return max(0, min(int(score), 100))
