from __future__ import annotations

from dataclasses import dataclass, field
from enum import IntEnum
from typing import Protocol


class RevisionStatus(IntEnum):
    PENDING = 0
    GENERATING = 1
    COMPLETED = 2
    FAILED = 3


def status_code_to_name(status: int) -> str:
    mapping = {
        int(RevisionStatus.PENDING): "pending",
        int(RevisionStatus.GENERATING): "generating",
        int(RevisionStatus.COMPLETED): "completed",
        int(RevisionStatus.FAILED): "failed",
    }
    return mapping.get(int(status), "pending")


@dataclass(slots=True)
class GeneratedRevisionItem:
    task_id: str
    utterance_seq: int
    speaker: str | None
    start_time: int
    end_time: int
    original_text: str
    suggested_text: str
    suggested_cue: str | None
    draft_text: str | None = None
    draft_cue: str | None = None
    score: int = 0
    issue_tags: list[str] = field(default_factory=list)
    explanations: list[str] = field(default_factory=list)


@dataclass(frozen=True, slots=True)
class RevisionPromptUtterance:
    utterance_seq: int
    speaker: str | None
    text: str
    start_time: int
    end_time: int


@dataclass(frozen=True, slots=True)
class RevisionGenerateRequest:
    task_id: str
    user_prompt: str | None
    utterances: list[RevisionPromptUtterance]


@dataclass(slots=True)
class RevisionSuggestion:
    utterance_seq: int
    suggested_text: str
    suggested_cue: str | None
    score: int
    issue_tags: list[str] = field(default_factory=list)
    explanations: list[str] = field(default_factory=list)


class RevisionGenerator(Protocol):
    provider_name: str

    def generate(self, req: RevisionGenerateRequest) -> list[RevisionSuggestion]:
        ...


class FakeRevisionGenerator:
    provider_name = "fake"

    def generate(self, req: RevisionGenerateRequest) -> list[RevisionSuggestion]:
        suggestions: list[RevisionSuggestion] = []
        for item in req.utterances:
            suggestions.append(
                RevisionSuggestion(
                    utterance_seq=int(item.utterance_seq),
                    suggested_text="This is a fake revised sentence for debugging.",
                    suggested_cue="[自然的 / 平稳的 / 调试模式]",
                    score=78,
                    issue_tags=["调试文案"],
                    explanations=["Generated by FakeRevisionGenerator for local debugging."],
                )
            )
        return suggestions
